# k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
type: Opaque
data:
  # Upar se jo encoded values aayi, wo paste karo
  DATABASE_URL: cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpucGdfeGZqd0tuYlE1bUwyQGVwLWhvbHktc3Vuc2V0LWFoYjRjZGhxLXBvb2xlci5jLTMudXMtZWFzdC0xLmF3cy5uZW9uLnRlY2gvbmVvbmRiP3NzbG1vZGU9cmVxdWlyZQ==
  OPENROUTER_API_KEY: c2stb3ItdjEtZmUyZmNhMjhmZjI4YzA0ZWM3OGZjOTQ4MmQ0NTA5MTlmY2UxN2JjY2JkMDQ3ZDc2NjQ5MDE3OTUwYTk4ZjI5NA==
  BETTER_AUTH_SECRET: VTVMQ05vTi1NUGhLbUJGNFFsN3hkdUdqM01FUFU5Mm5Jak13N0NWenlvRTVPdGpKblRJN1A5NVNfMHVDSjlvanI5MA==