openapi: 3.0.3
info:
  title: AI Todo Chatbot API
  description: API for AI-powered todo chatbot functionality
  version: 1.0.0
  contact:
    name: Todo App Team
    email: team@todoapp.com

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.todoapp.com
    description: Production server

paths:
  /api/chat/message:
    post:
      summary: Send message to AI chatbot
      description: Send a user message to the AI chatbot and receive a response
      tags:
        - Chat
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - conversation_id
                - content
              properties:
                conversation_id:
                  type: integer
                  description: ID of the conversation
                  example: 1
                content:
                  type: string
                  description: The user's message content
                  maxLength: 4000
                  example: "Create a task to buy groceries"
      responses:
        '200':
          description: AI response to the user's message
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  role:
                    type: string
                    enum: [assistant]
                    example: "assistant"
                  content:
                    type: string
                    example: "I've created the task 'buy groceries' for you."
                  timestamp:
                    type: string
                    format: date-time
                    example: "2025-12-27T10:00:00Z"
                  metadata_json:
                    type: string
                    nullable: true
                    example: '{"tool_calls": ["create_task"]}'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '429':
          description: Rate limit exceeded

  /api/chat/conversations:
    get:
      summary: List user conversations
      description: Get a list of conversations for the authenticated user
      tags:
        - Chat
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of user conversations
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversations:
                    type: array
                    items:
                      $ref: '#/components/schemas/Conversation'
                  total:
                    type: integer
                    example: 5
        '401':
          description: Unauthorized

  /api/chat/conversations/new:
    post:
      summary: Create new conversation
      description: Create a new conversation for the authenticated user
      tags:
        - Chat
      security:
        - BearerAuth: []
      responses:
        '201':
          description: New conversation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '401':
          description: Unauthorized

  /api/chat/conversations/{id}:
    get:
      summary: Get conversation details
      description: Get details of a specific conversation
      tags:
        - Chat
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Conversation ID
      responses:
        '200':
          description: Conversation details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '401':
          description: Unauthorized
        '404':
          description: Conversation not found
    put:
      summary: Update conversation
      description: Update conversation details (e.g., title)
      tags:
        - Chat
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Conversation ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  maxLength: 200
                  example: "Task Management Chat"
      responses:
        '200':
          description: Conversation updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '401':
          description: Unauthorized
        '404':
          description: Conversation not found
    delete:
      summary: Delete conversation
      description: Delete a conversation and all its messages
      tags:
        - Chat
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Conversation ID
      responses:
        '204':
          description: Conversation deleted
        '401':
          description: Unauthorized
        '404':
          description: Conversation not found

  /api/chat/conversations/{id}/messages:
    get:
      summary: Get conversation messages
      description: Get all messages in a specific conversation
      tags:
        - Chat
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Conversation ID
      responses:
        '200':
          description: List of messages in the conversation
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/ChatMessage'
        '401':
          description: Unauthorized
        '404':
          description: Conversation not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Conversation:
      type: object
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 123
        title:
          type: string
          example: "Task Management Chat"
        created_at:
          type: string
          format: date-time
          example: "2025-12-27T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2025-12-27T10:00:00Z"
        is_archived:
          type: boolean
          example: false

    ChatMessage:
      type: object
      properties:
        id:
          type: integer
          example: 1
        conversation_id:
          type: integer
          example: 1
        role:
          type: string
          enum: [user, assistant]
          example: "user"
        content:
          type: string
          example: "Create a task to buy groceries"
        timestamp:
          type: string
          format: date-time
          example: "2025-12-27T10:00:00Z"
        metadata_json:
          type: string
          nullable: true
          example: null