apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: 8000